### ISSUE TITLE
pipeline-validator: Add validation for tag

### ISSUE THREAD

**Issue by mike-serchenia** [ElementalCognition/tekton-toolbox#318]
Pipeline validator must check tag values
e.g
pr section: body.pull_request.head.sha
main section: body.head_commit.id

```
pr:
          - name: tag
            value: string("0.0.0.0-") + string(body.pull_request.head.sha).truncate(7)
main:
         - name: tag
            value: string("0.0.0.0-") + string(body.head_commit.id).truncate(7)
```
